version: "3.1"

services:
  rabbitmq:
    image: rabbitmq:3.5.3-management
    ports:
      - 5672:5672
      - 15672:15672
  springboot-rabbitmq:
    build: .
    environment:
      - SPRING_RABBITMQ_ADDRESSES=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    ports:
      - 8080:8080

